In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from scipy.spatial import distance
from scipy.sparse import csr_matrix
from numpy import transpose

In [14]:
def TSCAN(path: list, X: list):
    v12 = np.array(path[1]).reshape(-1,1) -np.array(path[0]).reshape(-1,1)
    project_value_list1 = []
    for item in X[0]:
        x1 = np.array(item).reshape(-1,1)  - np.array(path[0]).reshape(-1,1)
        project_value1 = (x1.T@(v12))/(v12.T@v12) 
        project_value_list1.append(project_value1)

    
    v_last = np.array(path[-1]).reshape(-1,1)-np.array(path[-2]).reshape(-1,1)
    project_value_list_last = []
    for item in X[-1]:
        x_last = np.array(item).reshape(-1,1)  - np.array(path[-1]).reshape(-1,1)
        project_value_last = (x_last.T@(v_last))/(v_last.T@v_last) 
        project_value_list_last.append(project_value_last)

    lists = []
    for i in range(1, len(path)-1):
        project_value_list_minus = []
        project_value_list_add = []

        v_minus = np.array(path[i]).reshape(-1,1)-np.array(path[i-1]).reshape(-1,1)
        v_add = np.array(path[i+1]).reshape(-1,1)-np.array(path[i]).reshape(-1,1)
        for item in X[i]:
            d1 = np.linalg.norm(np.array(item) - path[i-1])
            d2 = np.linalg.norm(np.array(item) - path[i+1])
            xi = np.array(item).reshape(-1,1) - np.array(path[i]).reshape(-1,1)
            if d1 < d2:
                project_value_minus = (xi.T@(v_minus))/(v_minus.T@v_minus)
                project_value_list_minus.append(project_value_minus)
                
            else:
                project_value_add = (xi.T@(v_add))/(v_add.T@v_add)
                project_value_list_add.append(project_value_add)
                
            combine = (project_value_list_minus, project_value_list_add)
        lists.append(combine)
        flat_lists = list(np.concatenate(lists).flat)
        remove_empty = [x for x in flat_lists if x]
        project_value_int = list(np.concatenate(remove_empty).flat)
        

        
    order_c1 = np.argsort(np.array(project_value_list1).reshape(1, -1))
    order_c1_list = order_c1[0].tolist()
    
    cell_order_int = np.argsort(np.array(project_value_int, dtype=object).reshape(1, -1))
    order_int = cell_order_int[0] + max(order_c1[0])
    order_int_list = order_int.tolist()
    
    
    cell_order_last = np.argsort(np.array(project_value_list_last,dtype=object).reshape(1, -1))
    order_last = cell_order_last[0]+max(order_int)
    order_last_list = order_last.tolist()
    
    
    
    orders_combine = order_c1_list + order_int_list + order_last_list
    orders = np.transpose(orders_combine)
        
    return orders
        


In [3]:
data = pd.read_csv("matrixnby2.csv")
matrix = np.array(data)
kmeans = KMeans(n_clusters=8)
kmeans.fit(matrix)
y_kmeans = kmeans.predict(matrix)

In [4]:
centers = kmeans.cluster_centers_
centers

array([[438.83971132, 117.78940679],
       [213.99702944, 104.94821859],
       [224.63789116, 194.72322871],
       [137.46413095,  27.25532951],
       [412.43623236,  36.82976272],
       [367.56214742,  88.15213929],
       [316.80929527,  -9.44481174],
       [488.20388805,  22.6778282 ]])

In [5]:
path = ([334.52337703,  -5.73041852],
       [213.99702944, 104.94821859],
       [440.93488623, 129.51162243],
       [137.46413095,  27.25532951],
       [224.63789116, 194.72322871],
       [362.60511513,  88.34787612],
       [488.20388805,  22.6778282 ],
       [419.55208667,  59.91444152])



labels = kmeans.labels_
labels

array([3, 1, 3, 3, 3, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 0, 4, 5, 0, 7, 0, 0, 5, 5, 7, 4, 4, 5, 4, 6, 7, 4, 0, 7,
       5, 0, 6, 6, 4, 5, 0, 7, 5, 5, 7], dtype=int32)

In [6]:
c1_points_position = list(np.where(labels == 0)[0])
c2_points_position = list(np.where(labels == 1)[0])
c3_points_position = list(np.where(labels == 2)[0])
c4_points_position = list(np.where(labels == 3)[0])
c5_points_position = list(np.where(labels == 4)[0])
c6_points_position = list(np.where(labels == 5)[0])
c7_points_position = list(np.where(labels == 6)[0])
c8_points_position = list(np.where(labels == 7)[0])
x1 = [matrix[ele] for ele in c1_points_position ]
x2 = [matrix[ele] for ele in c2_points_position ]
x3 = [matrix[ele] for ele in c3_points_position ]
x4 = [matrix[ele] for ele in c4_points_position ]
x5 = [matrix[ele] for ele in c5_points_position ]
x6 = [matrix[ele] for ele in c6_points_position ]
x7 = [matrix[ele] for ele in c7_points_position ]
x8 = [matrix[ele] for ele in c8_points_position ]

In [7]:
X=(x1,x2,x3,x4,x5,x6,x7,x8)


In [8]:
v12 = centers[0].reshape(-1,1)-centers[1].reshape(-1,1)
v23 = centers[2].reshape(-1,1)-centers[1].reshape(-1,1)
v34 = centers[3].reshape(-1,1)-centers[2].reshape(-1,1)

In [15]:
TSCAN(path, X)

array([ 1,  6,  0,  2,  3,  4,  5, 47, 21, 24, 25, 22, 18, 23, 19, 26, 17,
       20, 46, 45, 37, 13,  9, 11, 38, 29, 10, 30, 12, 39, 16, 28, 42, 14,
       43,  8,  7, 27, 15, 41, 44, 40,  6, 33, 35, 31, 36, 34, 32, 51, 50,
       52, 48, 49, 47])